name: Build Electron App

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Remove old dist
        run: |
              echo "Deleting old dist folder..."
              rm -rf $GITHUB_WORKSPACE/dist
              mkdir -p $GITHUB_WORKSPACE/dist

      - name: Check dist folder after cleanup
        run: ls -alh $GITHUB_WORKSPACE/dist || echo "dist is empty"

      - name: Install Dependencies
        run: npm ci

      - name: Remove old dist
        run: rm -rf dist

      - name: Clean electron-builder workspace cache
        run: rm -rf ${{ github.workspace }}/.cache

      - name: Build project
        env:
          ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache
        run: npm run build:linux

      - name: Upload Linux Installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: dist/**

      - name: Inspect linux-unpacked size
        run: du -sh dist/linux-unpacked/resources/app/node_modules/*
